### ISSUE TITLE
Plugin treat lower case as different value

### ISSUE THREAD

**Issue by vram001** [snuids/jVectorMapKibanaCountry#1]
Recently found situation where vis started showing wrong count for countries; instead of showing US, Count 30K, was showing just 1 for count. 
Reason was that one document had country='us' in lower case instead of 'US'. To bypass situation just updated country for that document back to uppercase, 'US' and count was back to normal.

**Comment by snuids** [comment]
If I have 5 minutes to spare, I will add a lowercase/uppercase option which sounds reasonable.

**Comment by snuids** [comment]
Solved in the latest version via the checkbox "Normalize Input To UpperCase"
